require("rohith_namespace.set")
require("rohith_namespace.remap")
require("rohith_namespace.gitsigns")
require("rohith_namespace.lightline")
-- require('rohith_namespace/telescope')
-- require('rohith_namespace/lightline')
-- require('rohith_namespace/gitsigns')
-- require('rohith_namespace/lsp')
-- require('rohith_namespace/treesitter')

